version: '2'
services:
  main:
    build:
      context: .
      args:
        ELASTICSEARCH_IP: $ELASTICSEARCH_IP
    depends_on:
      - registrator
    ports:
      - "5000:5000/udp"
      - "12201:12201/udp"
      - "9600:9600/tcp"
    environment:
      ELASTICSEARCH_IP: $ELASTICSEARCH_IP
    labels:
      - 'SERVICE_9600_NAME=logstash'
      - 'SERVICE_9600_CHECK_HTTP=/'
      - 'SERVICE_9600_CHECK_INTERVAL=15s'
      - 'SERVICE_9600_CHECK_TIMEOUT=3s'
      - 'SERVICE_5000_NAME=logstash-udp'
      - 'SERVICE_12201_NAME=logstash-gelf'
      - 'SERVICE_TAGS=external,kong'

  registrator:
    image: gliderlabs/registrator
    command: consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - consul

  consul:
    image: consul:latest
    ports:
      - '8400:8400'
      - '8500:8500'
      - '8600:53/udp'
    labels:
      SERVICE_IGNORE: 'true'  # Do not add any of Consul's services to Consul's service discovery registry.
    command: [agent, '-server', '-ui', '-bootstrap', '-client=0.0.0.0']

