version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/build

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deployment script
          command: |
            export azureswarm_branch=develop
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then export azureswarm_branch=master; fi
            curl -f --header "Authorization: token $GIT_TOKEN" https://raw.githubusercontent.com/gr4per/azureswarm/$azureswarm_branch/buildscript.sh > buildscript.sh
            chmod +x buildscript.sh
            ./buildscript.sh opuscapita/$CIRCLE_PROJECT_REPONAME

  mirror:
    docker:
      - image: circleci/node:8
    working_directory: ~/build

    steps:
      - checkout
      - run:
          name: Mirror Script
          command: |
            export azureswarm_branch=develop
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then export azureswarm_branch=master; fi
            curl -f --header "Authorization: token $GIT_TOKEN" https://raw.githubusercontent.com/gr4per/azureswarm/$azureswarm_branch/mirrorscript.sh > mirrorscript.sh
            chmod +x mirrorscript.sh
            ./mirrorscript.sh opuscapita/$CIRCLE_PROJECT_REPONAME $FROM_ENV $TO_ENV

  build_base:
    docker:
      - image: circleci/node:8
    working_directory: ~/build

    steps:
      - checkout
      - setup_remote_docker
      - deploy:
          name: Build and push Docker base image
          command: |
            docker build -t opuscapita/$CIRCLE_PROJECT_REPONAME:base -f Dockerfile.base .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push opuscapita/$CIRCLE_PROJECT_REPONAME:base

